### ISSUE TITLE
Status of this repo?

### ISSUE THREAD

**Issue by jgeluk** [PaulTraynor/L4-Project-Rust-TAPS-Implementation#1]
Status of this project? 1 developer, hobby project or more serious? Roadmap, team?
Would like to use it but trying to avoid being locked-in to something that turns out to be abandoned..

**Comment by PaulTraynor** [comment]
Hi Jacobus, thanks for checking my project out. This was my final year individual university project, it's finished for now. I plan to extend it further in my free time when exams etc. are done and I have time. Happy to answer any other questions.

**Comment by PaulTraynor** [comment]
To be clear, I plan to get a stable release in the coming months once I can start working on it again, then it will be ready for use. As well as documentation and upload to crates.io of course.
